site_name: Tiếng Hàn - Khu học mở
site_description: Một hướng dẫn tự học Tiếng Hàn thông qua Comprehensible Input và Immersion.
site_author: duykhanh471  
site_url: https://daihocmo.github.io
repo_url: https://github.com/daihocmo/tieng-han
repo_name: Đóng góp chỉnh sửa trang

nav:
  - 'Trang chủ': 'index.md'
  - 'Hướng dẫn': 'guide.md'
  - 'Immersion': 'immersion.md'
  - 'Tài nguyên học': 'learning-resources.md'
  - 'Tổng hợp': 'resources.md'
      
theme:
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: grey
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: grey
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: img/logo.png
  favicon: img/logo.png
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.suggest
    - search.highlighting
    - search.share
  name: material

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - meta
  - admonition
  - attr_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
      
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false